repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: check-pdb
        name: check for pdb
        entry: python -c "import sys; [sys.exit(1) for f in sys.argv[1:] if 'pdb' in open(f).read()]"
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: [--branch=main, --branch=dev]
      - id: detect-private-key
      - id: debug-statements
      - id: check-shebang-scripts-are-executable
      - id: check-case-conflict

  - repo: https://github.com/commit-check/commit-check
    rev: v2.3.0
    hooks:
      - id: check-message
